### PR TITLE
Gift Entry:  Populate Linked Fields for Lookups

### LINKED ISSUE #5208: Gift entry: Open in batch table throwing component error when allocation widget is present and no allocation is added.
Details and Steps to Reproduce:-
1. Create a template with Allocation bundle.
2. Create/open a batch with the same template.
3. Add a gift in the batch without any allocation. A new row should be added to the table.
4. Click "Open" in the same row to open the gift from the row in batch gift form.

Expected result:
Form loads with data from row

Actual result:
Component error
Screen Shot 2020-02-26 at 10 08 27 AM

### PR DESCRIPTION
**Pull request by kenlewis-sfdo**
This set of changes populates sibling fields when lookups are given a value, via user-selection or via loading an id into a lookup field.  

When a Payment is selected in the Review Donations modal, the Donation Amount and Donation Date fields are overridden with values from the selected Payment record. 

Linked field are identified by reading field mappings that share the same parent object mapping as that of the lookup field being populated.

Also fixes:
W-039801: https://foundation.lightning.force.com/lightning/r/agf__ADM_Work__c/a2x1E000001HsrhQAC/view
And
W-039797: https://foundation.lightning.force.com/a2x1E000001HsrNQAS

# Critical Changes

# Changes
## Gift Entry Enhancements
- We added functionality to make it easy to update a record while entering a gift. Now, when you select a Contact, Account, or any other record in a lookup field, all of the other fields on the form that are linked to that record will show the current information. Update any of it within the Gift Entry form and those updates will be reflected on the record once you process the gift.

# Issues Closed

- Fixes #5208

# Community Ideas Delivered

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by kenlewis-sfdo** [comment]
**lurch: attach W-039031

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HrMQQA0" target="_blank">W-039031</a>

**Comment by ptewson-sfdo** [comment]
Hi @kenlewis-sfdo - just seeing a couple issues while testing this out functionally. The first is when I hit "Cancel and Clear Form" on an empty form, I get this: 
image

**Comment by ptewson-sfdo** [comment]
I also get this when I attempt to open a row from the BGE table (all this testing is with the default form) - 
image

**Comment by dfuller114** [comment]
@ptewson-sfdo looks like we currently have a regression in the GAU widget in this PR. currently investigating the cause.

**Comment by kenlewis-sfdo** [comment]
**lurch: attach W-039801

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HsrhQAC" target="_blank">W-039801</a>

File: src/lwc/geFormFieldLookup/geFormFieldLookup.js [hunk 1]
```diff
@@ -1,16 +1,18 @@
 import { LightningElement, api, wire, track } from 'lwc';
 import { getObjectInfo } from 'lightning/uiObjectInfoApi';
-import { getRecord, getFieldValue } from 'lightning/uiRecordApi';
+import { getRecord } from 'lightning/uiRecordApi';
 import doSearch from '@salesforce/apex/GE_LookupController.doSearch';
 import { isNotEmpty } from 'c/utilCommon';
+import { handleError } from 'c/utilTemplateBuilder';
 
 const DELAY = 300;
```
Comment (ptewson-sfdo) [inline src/lwc/geFormFieldLookup/geFormFieldLookup.js]: Not for this PR/story, but we should think long term how to avoid timing-based delays and setTimeout for a future improvement

File: src/lwc/geFormFieldLookup/geFormFieldLookup.js [hunk 2]
```diff
@@ -165,14 +189,30 @@ export default class GeFormFieldLookup extends LightningElement {
 
     @api
     setSelected(lookupResult) {
-        const lookup = this.template.querySelector('c-ge-autocomplete');
-        lookup.setLookUpData(lookupResult);
+       if (lookupResult.value === null) {
```
Comment (ptewson-sfdo) [inline src/lwc/geFormFieldLookup/geFormFieldLookup.js]: I think this block should be one more space indented (through line 200)

File: src/lwc/geFormWidget/geFormWidget.js [hunk 3]
```diff
@@ -59,4 +61,16 @@ export default class GeFormWidget extends LightningElement {
...
     }
+
+    /**
+     * @description This method should return a list of DataImport__c field api names
+     *              that the widget uses so that parent components (geFormSection) know
+     *              which fields to include when calling this component's load() function.
+     * @returns An Array of field names used by this component.
+     */
+    @api
+    get allFieldsByAPIName() {
```
Comment (ptewson-sfdo) [inline src/lwc/geFormWidget/geFormWidget.js]: Should this come from the geFormWidgetAllocation and be passed up here? Just thinking ahead to other widgets that aren't necessarily using this same field

File: src/lwc/geFormFieldLookup/geFormFieldLookup.js (hunk 2 above)
Comment (kenlewis-sfdo) [reply src/lwc/geFormFieldLookup/geFormFieldLookup.js]: 👍🏽

File: src/lwc/geFormWidget/geFormWidget.js (hunk 3 above)
Comment (kenlewis-sfdo) [reply src/lwc/geFormWidget/geFormWidget.js]: Yep!  Will move it

File: src/lwc/geFormField/geFormField.js [hunk 4]
```diff
@@ -330,28 +329,33 @@ export default class GeFormField extends LightningElement {
     load(data) {
```
[the remark this answers is not in the document]
Comment (kenlewis-sfdo) [reply src/lwc/geFormField/geFormField.js]: Agreed.  Very open to discussing this and strategizing about the best way to do it for a future refactor.

File: src/lwc/geFormField/geFormField.js [hunk 5]
```diff
@@ -330,28 +329,33 @@ export default class GeFormField extends LightningElement {
...
         let value;
         if (data.hasOwnProperty(this.sourceFieldAPIName)) {
-            if (data[this.sourceFieldAPIName].hasOwnProperty('value')) {
-                value = data[this.sourceFieldAPIName].value;
+            value = data[this.sourceFieldAPIName];
+            if (value === null || value.value === null) {
+                this.reset();
             } else {
-                value = data[this.sourceFieldAPIName];
+                this.value = value.value || value;
```
[the remark this answers is not in the document]
Comment (kenlewis-sfdo) [reply src/lwc/geFormField/geFormField.js]: Yeah, part of the reason this is needed is because of how the lookup display values are saved on each row in the table and then need to be loaded into the form.  This should def be part of the larger convo about how the data structures should be composed for the load function.

**Comment by kenlewis-sfdo** [comment]
**lurch: attach W-039797

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HsrNQAS" target="_blank">W-039797</a>

**Comment by kenlewis-sfdo** [comment]
@melissabarber Thank you for updating the PR description-  Looks good.  And yes, the issue referenced as closed/fixed is correct.  Thank you!
