### PR TITLE
Block user edit of Default GAU row on allocation widget

### LINKED ISSUE #5824: Unable to specify percentage on default GAU in GE form
**WI**: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008ITRkIAO/view

**Description**

In the GE/BGE form, if a default GAU is set for your org, the percentage form field for the GAU is disabled and you can only 100% match the donation amount for the GAU. However, if a second GAU is added to the form, both the Percent and Amount fields can be used for the second GAU.

**Steps to Reproduce**

1. Create two General Allocation Units
2. Navigate to NPSP settings > Donations > GAU Allocations and enable the default GAUs setting
3. Search for and set the default GAU to one of the GAUs you created in step one
4. Navigate to Gift Entry and open the default template
5. Add the GAU widget to the template and save it
6. Click 'New Gift'
7. Enter a donation amount. Amount field will automatically fill with the whole donation amount and Percent field will be greyed out.
8. Click Add New Allocation and add the second GAU created in step one.
9. The second GAU can use either the percentage or amount field.

### LINKED ISSUE #6066: 'Donation does not match' GAU banner displays after reopening matching gifts
### Description
If a batch gift with a GAU allocation that matches the gift amount exactly is saved and reopened, the 'Total amount does not match the donation amount' banner displays in the gift form, despite the amounts matching. This does not affect gift processing.

image

### Steps to Reproduce

1. Open a batch or create a new batch
2. Enter donor information (Donor Type and Contact/Account)
3. Enter donation date and amount.
4. Click 'Add New Allocation'
5. Select a GAU.
6. Enter an amount for the allocation that matches the gift amount.
7. Click 'Save & Enter New Gift'
8. Open the menu in the BGE table for the gift you just created and click 'Open'.
9. The gift is reopened in the form, and the 'Total amount does not match the donation amount' banner displays for the GAU allocation, despite the amounts matching exactly.

GUS WI: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008jPXYIA2/view

### LINKED ISSUE #6385: Gift Entry - Changing the Default GAU and Editing the Allocation Amount Freezes Browser Window
**Issue**
In NPSP Settings when a default GAU is set, and when using Gift Entry with the GAU Allocation Bundle, making changes to the GAU that is automatically populated (the default) and the allocated amount, immediately locks up the browser upon changing a whole digit in the Amount field. The page becomes unresponsive and clicking the "wait" option when it appears does not result in the change completing, and the page has to be killed.

**Note:** gif is 37 seconds so continue to wait after amount field is entered to see window lock up

**Steps to Recreate**
1. In NPSP Settings > Donations > GAU Allocations > set a Default Allocations Enabled to True and select a Default General Accounting Unit
2. Navigate to Gift Entry and ensure that the template being used by Single Gift Entry (typically it is the Default Gift Entry Template) contains the "GAU Allocations" bundle from under the Form Fields header > Field Bundles
3. Start a Single Gift Entry
4. Notice that the "General Accounting Unit" field at the bottom of the page in the bundle is populated with the Default GAU
5. Fill in the bare minimum fields, and notice that upon entering a value into the Donation Amount field, the Amount field on for the GAU Allocation auto-populated
6. Change the General Accounting Unit from the default to another in the org
7. Click into the Amount field next to the General Accounting Unit and attempt to delete or add a single (whole, not decimal) digit
8. The browser will lock, and you will be unable to interact with the form any further resulting in the need to click the "kill" option when the window provides you with it after several seconds

**Workaround**
Using the manual General Accounting Unit and GAU Allocation fields that can be added to a template will allow the entering of allocations without the auto-population of the default GAU.

### PR DESCRIPTION
**Pull request by ptewson-sfdo**
This resolves an issue with the GAU Allocations Field Bundle on the gift entry form that presents when the Default GAU is set in NPSP settings, where the user was allowed to incorrectly modify and replace the default GAU allocation. Following this change the default GAU row will be read-only in the allocations field bundle.

# Critical Changes

# Changes

# Issues Closed
Fixes #6480
Fixes #6385
Fixes #5824
Fixes #6066 

# Community Ideas Delivered

# Features Intended for Future Release

# Features for Elevate Customers

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Review by sokosaurus — APPROVED** [review]
Loaded this up in a scratch org and ran through a few quick tests. Code looks solid! Great work.

**Review by psadie-sfdo — APPROVED** [review]
This looks good to me as well!

Just one thing that Patrick and I already sync'd up on regarding rows being removed from the UI when the user changes the donation amount field and they've added empty allocation rows. I believe we'll need a follow-up work item to handle that separately.

File: src/lwc/geFormWidgetAllocation/geFormWidgetAllocation.js [hunk 1]
```diff
@@ -110,12 +114,7 @@ export default class GeFormWidgetAllocation extends LightningElement {
     }
 
     get hasRemainingAmount() {
-        return this.allocationSettings[ALLOC_SETTINGS_DEFAULT_ALLOCATIONS_ENABLED] &&
-            this.remainingAmount >= 0;
-    }
-
-    hasAllocations() {
-        return Array.isArray(this.rowList) && this.rowList.length > 0;
+        return this.hasDefaultGAU && this.remainingAmount >= 0;
```
Comment (kenlewis-sfdo) [inline src/lwc/geFormWidgetAllocation/geFormWidgetAllocation.js:117]: Much cleaner!
